### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by crimes2** [yuyingke/wang-zhe-rong-yao#1]

**Comment by yuyingke** [comment]
安装python3，配置ADB命令环境，手机或模拟器开启ADB调试，进入王者荣耀冒险模式最高难度最后一关，就可以双击autotap.py运行了

**Comment by crimes2** [comment]
oh,感谢我以为是进游戏就能用,我双击它一直闪退.

**Comment by crimes2** [comment]
运行出错啦？
`C:\Users\Administrator>py C:\Users\Administrator\Desktop\autotap.py
  File "C:\Users\Administrator\Desktop\autotap.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax`

**Comment by yuyingke** [comment]
百度搜索python  subprocess,需要安装支持包,缺少支持库
________________________________

**Comment by yuyingke** [comment]
还需要实际按照手机分辨率去配置点击坐标值和延时时间，因为每个手机的性能不一样

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yuyingke** [comment]
对了，在 cmd 中输入 adb 是否有反应，如果提示找不到命令可能就是没配置adb，需要配置adb

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
